### ISSUE TITLE
Keptn Roadmap 2.0

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#154]
We want to scale-up the roadmap to integrate more stories in the ecosystem

## Links

- https://github.com/orgs/keptn/projects/10

## Scope

- [x] Switch to the new GitHub projects documentation
- [ ] Integrations roadmap
- [ ] UI/UX items roadmap
- [ ] Update the external links to the roadmap
