### ISSUE TITLE
Introduce the community roadmap

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#67]
It would be nice to create a GitHub project that provides a non-technical community roadmap

## Acceptance criteria

- [x] Key community issues are created in the repositories
- [x] There is a GitHub project that allows navigating the roadmap: https://github.com/orgs/keptn/projects/1
- [x] Community roadmap is referenced in ROADMAP.md files where relevant
- [x] Community roadmap is reviewed at Keptn community meetings and signed off there
- [x] There is a public announcement

**Comment by oleg-nenashev** [comment]
https://keptn.sh/docs/roadmap/ also needs to be updated
