### ISSUE TITLE
Keptn on community.cncf.io

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#71]
Follow-up to the Zoom account transfer to the CNCF we initiated a couple of weeks ago. I discussed that with the foundation, and their recommendation is to regular switch to the community portal provided by the Linux Foundation as a part of the LFX toolchain. They plan to make this platform GA by February but it's already available for evaluation. We could try using it in Keptn.

This is a new platform based on Bevy that intends to aggregate community events under a single roof, including meetup.com alike portal and Zoom replacement. As with other Linux Foundation services, the final mileage may vary.

Currently it's still possible to request the zoom accounts but it will be a deprecated option soon. So I wonder whether we should give it a try and start building the proof of concept around the new platform. We don't have so many external participants at the moment, and from what I see in the documentation Bevy supports YouTube broadcasts.

## Check list

- [x] - Request an org. A maintainer needs to submit the request
- [x] - Get initial content created: https://community.cncf.io/keptn-community/ 
- [x] - Configure Bevy. Get @oleg-nenashev and Giulia Di Pietro added to the team
- [x] - Update the website - https://github.com/keptn/keptn.github.io/pull/990
- [x] - Update the Keptn Calendar
- [ ] - Update the CNCF calendar
- [x] - Announce the new platform
- [x] - Run a test meetup on the platform

**Comment by oleg-nenashev** [comment]
FTR CNCFSD-1028 was created by @grabnerandi and then handled by @idvoretskyi.
I cannot see the chapter on the portal at the moment, I will try to figure out the next steps

**Comment by oleg-nenashev** [comment]
NVM, actually it is https://community.cncf.io/keptn-community/ . On it

**Comment by idvoretskyi** [comment]
> actually it is https://community.cncf.io/keptn-community/ 

Correct, let me know if you need any help with it.

**Comment by oleg-nenashev** [comment]
Thanks @idvoretskyi! I have a few minor issues with data inconsistency but everything looks good otherwise

**Comment by oleg-nenashev** [comment]
I think we're fine. Moved over to Bevy, so far so good
