### ISSUE TITLE
Keptn Public Demo 2.0

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#89]
### Proposal

Keptn Public Demo was shut down on Dec 23.  (https://keptn.public.demo.keptn.sh/). Apart from Log4J, there are other issues including the corrupted database and general security concerns about the instance until KEP-60 "RBAC for Keptn" is implemented (see https://github.com/keptn/enhancement-proposals/pull/60 ). The instance will remain shut down over the Christmas break.

TODOs:

- [ ] - Update the documentation and tutorials accordingly
- [ ] - Start a new repository for a new Demo Keptn setup, fully managed -as-code via GitOps
- [ ] - Rollout the new demo cluster
- [ ] - Update the documentation

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### Checklist

- [x] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by oleg-nenashev** [comment]
FTR Keptn GitOps KEP-65 is now submitted by @christian-kreuzberger-dtx : https://github.com/keptn/enhancement-proposals/pull/67 . I think we could use this public demo cluster as a reference implementation

**Comment by thschue** [comment]
Currently, no new public demo cluster is planned and for demo purposes, the Killercoda environments should be enough. Therefore closing this issue.
